# Alembic configuration.
[alembic]
# path to migration scripts
scriptLocation = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be named with an absolute path
# fileNameTemplate = /some/absolute/path/%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to datetime.datetime.now().astimezone() to select
# an appropriate timezone.  Use the value as returned by some date/time library
# num value (nonnegative) to select the nth timezone from the tzinfo.TZINFO_DATABASE
# leave unset to use localtime
# timezone =

# max length of characters to apply to the
# "slug" field when generating a migration file
# name. The default value is 40, which means will
# take the first 40 characters of the
# provided migration message.
#
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# Loggers to configure, one or more space separated logger names
# loggers = sqlalchemy.engine

# logging configuration
[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (ext://sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
